# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MCpbt <- function(iter, burnIn, thin, seed, Nclip, Nunclip, clipPrior, clippedBool, piTotPrior, ohnc, piTotInitial, oUTInitial, groups, nPBT, GSI_values, gsiUT, pi_gsiInitial, prior_pi_gsi, ohnc_gsi, values, pi_VInitial, pi_Vohnc, pi_Vprior, v_ut, initZ, t) {
    .Call(`_devMCpbt_MCpbt`, iter, burnIn, thin, seed, Nclip, Nunclip, clipPrior, clippedBool, piTotPrior, ohnc, piTotInitial, oUTInitial, groups, nPBT, GSI_values, gsiUT, pi_gsiInitial, prior_pi_gsi, ohnc_gsi, values, pi_VInitial, pi_Vohnc, pi_Vprior, v_ut, initZ, t)
}

